<template>
  <div class="demo-icons">
    <AcademyPreviewIcon size="m" color="#C2C3D8" />
    <AccountingIcon size="s" color="#6F53DB" />
    <AddCalendarIcon size="m" color="#9394AF" />
    <AddFilterIcon size="m" color="#6D6E8F" />
    <AddMailIcon size="m" color="#36365F" />
    <AddPeopleIcon size="m" color="#C2C3D8" />
    <AddIcon size="m" color="#6F53DB" />
    <AiIcon size="m" color="#9394AF" />
    <AlarmBellIcon size="m" color="#6D6E8F" />
    <AnalyticsAltIcon size="m" color="#36365F" />
    <AnalyticsPiechartIcon size="m" color="#C2C3D8" />
    <AnalyticsIcon size="s" color="#6F53DB" />
    <AntiqueIcon size="m" color="#9394AF" />
    <AppWindowRefreshIcon size="m" color="#6D6E8F" />
    <ArchiveIcon size="m" color="#36365F" />
    <ArrowDownIcon size="m" color="#C2C3D8" />
    <ArrowLeftLineIcon size="m" color="#6F53DB" />
    <ArrowLeftIcon size="m" color="#9394AF" />
    <ArrowReturnIcon size="m" color="#6D6E8F" />
    <ArrowRight1Icon size="m" color="#36365F" />
    <ArrowRightIcon size="m" color="#C2C3D8" />
    <ArrowUpIcon size="m" color="#6F53DB" />
    <AttachmentIcon size="m" color="#9394AF" />
    <AudioVerticalIcon size="m" color="#6D6E8F" />
    <AvatarUserIcon size="m" color="#36365F" />
    <AverageIcon size="m" color="#C2C3D8" />
    <AxeIcon size="m" color="#6F53DB" />
    <BugIcon size="m" color="#9394AF" />
    <BulbIcon size="m" color="#6D6E8F" />
    <CalendarClockIcon size="m" color="#36365F" />
    <CalendarSeriesIcon size="m" color="#C2C3D8" />
    <CalendarIcon size="m" color="#6F53DB" />
    <CardPaymentIcon size="l" color="#9394AF" />
    <CategoryIcon size="m" color="#6D6E8F" />
    <CertificateIcon size="l" color="#36365F" />
    <CheckBoxIcon size="m" color="#C2C3D8" />
    <CheckIcon size="m" color="#6F53DB" />
    <CircleAddIcon size="l" color="#9394AF" />
    <CircleCheckIcon size="m" color="#6D6E8F" />
    <CircleXIcon size="l" color="#36365F" />
    <ClearStylesIcon size="m" color="#C2C3D8" />
    <CloseIcon size="m" color="#6F53DB" />
    <CloudDownloadIcon size="m" color="#9394AF" />
    <CloudSyncIcon size="m" color="#6D6E8F" />
    <CompletedIcon size="m" color="#36365F" />
    <ComplianceIcon size="m" color="#C2C3D8" />
    <CopyPasteIcon size="m" color="#6F53DB" />
    <CopyPasteIcon size="m" color="#9394AF" />
    <CourseCategoryIcon size="m" color="#6D6E8F" />
    <CoursesIcon size="s" color="#36365F" />
    <CreateIcon size="m" color="#C2C3D8" />
    <CsvIcon size="m" color="#6F53DB" />
    <DashboardIcon size="m" color="#9394AF" />
    <DeleteIcon size="m" color="#6D6E8F" />
    <DiscoveryIcon size="m" color="#36365F" />
    <DocumentHorizontalIcon size="m" color="#C2C3D8" />
    <DocumentVerticalIcon size="m" color="#6F53DB" />
    <DownloadIcon size="m" color="#9394AF" />
    <DraftIcon size="m" color="#6D6E8F" />
    <DragDropIcon size="m" color="#36365F" />
    <DuplicateIcon size="m" color="#C2C3D8" />
    <ECommerceAltIcon size="m" color="#6F53DB" />
    <ECommerceIcon size="m" color="#9394AF" />
    <ELearningMonitorIcon size="m" color="#6D6E8F" />
    <EditIcon size="m" color="#36365F" />
    <EditorAlignCenterIcon size="xl" color="#C2C3D8" />
    <EditorAlignLeftIcon size="m" color="#6F53DB" />
    <EditorAlignRightIcon size="m" color="#9394AF" />
    <EditorArrowDownIcon size="m" color="#6D6E8F" />
    <EditorArrowLeftIcon size="m" color="#36365F" />
    <EditorArrowRightIcon size="m" color="#C2C3D8" />
    <EditorArrowUpIcon size="m" color="#6F53DB" />
    <EditorBoldIcon size="m" color="#9394AF" />
    <EditorBulletListIcon size="m" color="#6D6E8F" />
    <EditorCheckIcon size="m" color="#36365F" />
    <EditorDeleteIcon size="m" color="#C2C3D8" />
    <EditorFontSizeIcon size="m" color="#6F53DB" />
    <EditorFormulaIcon size="m" color="#9394AF" />
    <EditorImageIcon size="m" color="#6D6E8F" />
    <EditorItalicIcon size="m" color="#36365F" />
    <EditorLinkIcon size="xl" color="#C2C3D8" />
    <EditorNumberedListIcon size="m" color="#6F53DB" />
    <EditorQuoteIcon size="m" color="#9394AF" />
    <EditorRedoIcon size="m" color="#6D6E8F" />
    <EditorSubscriptIcon size="m" color="#36365F" />
    <EditorSuperscriptIcon size="m" color="#C2C3D8" />
    <EditorTextUnderlineIcon size="m" color="#6F53DB" />
    <EditorUndoIcon size="m" color="#9394AF" />
    <EditorUnlinkIcon size="xl" color="#6D6E8F" />
    <EnterIcon size="m" color="#36365F" />
    <ExpireWarningIcon size="l" color="#C2C3D8" />
    <ExportIcon size="m" color="#6F53DB" />
    <ExternalLinkIcon size="m" color="#9394AF" />
    <FolderIcon size="m" color="#6D6E8F" />
    <GrieferIcon size="l" color="#36365F" />
    <GroupIcon size="m" color="#C2C3D8" />
    <HelpIcon size="l" color="#6F53DB" />
    <HideIcon size="m" color="#9394AF" />
    <HtmlIcon size="m" color="#6D6E8F" />
    <ImageHorizontalIcon size="m" color="#36365F" />
    <ImageVerticalIcon size="m" color="#C2C3D8" />
    <InfoIcon size="m" color="#6F53DB" />
    <InvitationSentIcon size="m" color="#9394AF" />
    <InvoiceIcon size="xl" color="#6D6E8F" />
    <KeyboardEnterIcon size="s" color="#36365F" />
    <LayoutArrangeIcon size="m" color="#C2C3D8" />
    <LayoutListIcon size="m" color="#6F53DB" />
    <LayoutModuleIcon size="s" color="#9394AF" />
    <LicenceIcon size="m" color="#6D6E8F" />
    <LinkDiagonalIcon size="m" color="#36365F" />
    <LinkHorizontalIcon size="m" color="#C2C3D8" />
    <LiveCourseIcon size="m" color="#6F53DB" />
    <LiveTrainingIcon size="m" color="#9394AF" />
    <LoadingIcon size="m" color="#6D6E8F" />
    <LocationPinIcon size="m" color="#36365F" />
    <LockCourseIcon size="m" color="#C2C3D8" />
    <LogoutIcon size="m" color="#6F53DB" />
    <LongArrowDownIcon size="m" color="#9394AF" />
    <LongArrowUpIcon size="m" color="#6D6E8F" />
    <MailRemoveIcon size="xl" color="#36365F" />
    <MailSentIcon size="xl" color="#C2C3D8" />
    <MailIcon size="m" color="#6F53DB" />
    <MailingsIcon size="m" color="#9394AF" />
    <MemberIcon size="m" color="#6D6E8F" />
    <MenuIcon size="xl" color="#36365F" />
    <MinusIcon size="m" color="#C2C3D8" />
    <MoneyIcon size="m" color="#6F53DB" />
    <MoveAltIcon size="xl" color="#9394AF" />
    <MovieFileIcon size="m" color="#6D6E8F" />
    <NotesFlipIcon size="m" color="#36365F" />
    <NotesIcon size="m" color="#C2C3D8" />
    <OptionsIcon size="s" color="#6F53DB" />
    <PdfIcon size="m" color="#9394AF" />
    <PeopleIcon size="m" color="#6D6E8F" />
    <PercentageIcon size="m" color="#36365F" />
    <PerformanceIcon size="m" color="#C2C3D8" />
    <PictureSunIcon size="m" color="#6F53DB" />
    <PlusIcon size="m" color="#9394AF" />
    <PresentationIcon size="m" color="#6D6E8F" />
    <QuizAltIcon size="m" color="#36365F" />
    <QuizIcon size="m" color="#C2C3D8" />
    <RecurringIcon size="m" color="#6F53DB" />
    <RefreshIcon size="m" color="#9394AF" />
    <RemoveColorIcon size="m" color="#6D6E8F" />
    <RocketIcon size="m" color="#36365F" />
    <RoundArrowIcon size="m" color="#C2C3D8" />
    <ScormIcon size="m" color="#6F53DB" />
    <SearchIcon size="m" color="#9394AF" />
    <SendIcon size="m" color="#6D6E8F" />
    <SendingMailIcon size="m" color="#36365F" />
    <SettingsAltIcon size="m" color="#C2C3D8" />
    <SettingsIcon size="m" color="#6F53DB" />
    <ShareIcon size="m" color="#9394AF" />
    <ShoppingcartCheckIcon size="m" color="#6D6E8F" />
    <SmileyIcon size="m" color="#36365F" />
    <SsoIcon size="s" color="#C2C3D8" />
    <StarIcon size="m" color="#6F53DB" />
    <StyleIcon size="l" color="#9394AF" />
    <SuccessIcon size="m" color="#6D6E8F" />
    <SwitchAccountIcon size="m" color="#36365F" />
    <SynchroIcon size="m" color="#C2C3D8" />
    <TagIcon size="m" color="#6F53DB" />
    <TenantIcon size="m" color="#9394AF" />
    <TextformatIcon size="m" color="#6D6E8F" />
    <TimeIcon size="m" color="#36365F" />
    <TwoArrowsLeftIcon size="m" color="#C2C3D8" />
    <UploadDocIcon size="m" color="#6F53DB" />
    <UploadIcon size="m" color="#9394AF" />
    <UserIcon size="m" color="#6D6E8F" />
    <VideoVerticalIcon size="m" color="#36365F" />
    <VideoIcon size="m" color="#C2C3D8" />
    <ViewIcon size="m" color="#6F53DB" />
    <WaitingIcon size="m" color="#9394AF" />
    <WebhookIcon size="m" color="#6D6E8F" />
    <WorldIcon size="m" color="#36365F" />
    <WwwIcon size="m" color="#C2C3D8" />
    <XlsIcon size="m" color="#6F53DB" />
  </div>
</template>

<script setup lang="ts"></script>

<style lang="scss">
.demo-icons {
  margin-top: 2rem;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));
  gap: 1rem;
  align-items: center;
  justify-items: center;
}
</style>
