name: Build & Deploy playground

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        with:
          ref: main

      - name: Install dependencies
        run: npm install

      - name: Prepare playground
        run: npm run dev:prepare

      - name: Prepare playground
        run: npm run dev:build

      - name: Install dependencies in playground and generate static files
        run: |
          cd playground
          npm install
          npm run generate

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy build with rsync
        run: rsync -avz ./playground/.output/public/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/nuxt-compose-icons.arthurplazanet.com/
