name: Lint & Format & Test build

on:
  pull_request:

jobs:
  lint-format-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Lint
        run: npm run lint

      - name: Lint Style 
        run: npm run lint:style
           
      - name: Format 
        run: npm run format
       
      - name: Build the playground
        run: npm run dev:build