name: Lint & Format & Test build

on:
  push:
    branches: main

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    name: Node ${{ matrix.node }} sample
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm run lint
      - run: npm run format
      - run: npm run lint:style
      - run: npm run dev:build
